describe("scaffold", function()
    it("can require all data modules", function()
        assert.is_table(require("data.cities"))
        assert.is_table(require("data.periods"))
        assert.is_table(require("data.cards"))
        assert.is_table(require("data.roles"))
    end)

    it("can require all state modules", function()
        assert.is_table(require("src.state.gameState"))
        assert.is_table(require("src.state.profile"))
        assert.is_table(require("src.state.modifiers"))
    end)

    it("can require all rules modules", function()
        assert.is_table(require("src.rules.actions"))
        assert.is_table(require("src.rules.phases"))
        assert.is_table(require("src.rules.flux"))
        assert.is_table(require("src.rules.explosion"))
        assert.is_table(require("src.rules.winLose"))
    end)

    it("can require vendored binser", function()
        local binser = require("vendor.binser")
        assert.is_table(binser)
        assert.is_function(binser.serialize)
        assert.is_function(binser.deserialize)
    end)

    it("binser round-trips a simple value", function()
        local binser = require("vendor.binser")
        local data   = { name = "Temporal Anomaly", version = 1 }
        local bytes  = binser.serialize(data)
        local result = binser.deserialize(bytes)
        assert.equal(data.name, result[1].name)
        assert.equal(data.version, result[1].version)
    end)
end)
